### ISSUE TITLE
translation errors for devise and devise_invitable only displaying en.devise.failure.unauthenticated

### ISSUE THREAD

**Issue by thuy-econsys** [thuy-econsys/rails_app#2]
Per instructions from Devise Wiki [How To: Require admin to activate account before sign_in - Model changes](https://github.com/heartcombo/devise/wiki/How-To:-Require-admin-to-activate-account-before-sign_in#model-changes) `config/locales/devise.en.yml` was updated to include:
```yml
en:
  devise:
    registrations:
      user:
        signed_up_but_not_approved: 'You have signed up successfully but your account has not been approved by your administrator yet'
```

User model was updated to override **Devise::Models::Authenticatable** methods: 
```ruby
  def active_for_authentication? 
    super && approved? 
  end 
  
  def inactive_message 
    approved? ? super : :not_approved
  end
```

Initially there was an alert `translation missing: en.devise.failure.user.not_approved` so `config/locales/devise.en.yml` was updated to include:
```yml
en:
  devise:
      failure:
        user:
          not_approved: "Your account has not been approved by your administrator yet."
```

...but now changed and passing test for login:
```yaml
en:
  devise:
      failure:
        not_approved: "Your account has not been approved by your administrator yet."
```

Alerts displaying now are still only displaying `You need to sign in or sign up before continuing.` for signup:
```yml
en:
  devise:
     failure:
       unauthenticated: "You need to sign in or sign up before continuing."
```

Possible quirk having to do with also using `letter_opener` gem ¯\\_(ツ)_/¯
